---
# Create template from image provider
- name: "Import task to handle template import."
  include_tasks: import.yaml
  when:
    state|default('present') == 'present' and
    not template_exists

# Delete template
- name: "Import task to handle template deletion."
  include_tasks: destroy.yaml
  when:
    state|default('present') == 'absent' and
    template_exists

# Start a temporary vm and modify template
- name: "Import task to handle template modification."
  include_tasks: modify.yaml
  when:
    state|default('present') == 'present' and
    template_exists
