###############
# Engine vars #
###############
## The default username for the Engine (default: "admin@internal")
engine_username: ""

## Engine password
engine_password:

## Engine endpoint (ends with /ovirt-engine)
engine_endpoint:

## The datacenter name (default: "Default")
engine_datacenter_name: ""

## The Cluster name. (default: "Default")
engine_cluster_name: ""


#################
# Template vars #
#################
## The Template name to use (default: "k8s")
template_name:

## The Storage domain to import the Template to (default: "data")
template_storage_location: ""

## Import timeout . Increase this if your import fails. (default: 300)
template_import_timeout:

## Description of the imported template. (default: "Created by haikoo")
template_description:

## Extra repos to add to the template. (default: none)
#template_extra_repos: {}
#  - name: "REPONAME"
#    url: "REPOURL"
#    gpgkey: "REPO_GPG_KEY"

## Upgrade all packages on the template at runtime (default: True)
template_upgrade_packages: True

## Timezone of the imported template. (default: "Etc/GMT")
template_timezone:

## Install extra packages. (default: none)
template_extra_packages: []

## Extra commands to run (default: none)
template_extra_commands: []

## Extra systemd services to enable (default: none)
template_extra_services: []

## Enable SELINUX (default: False)
template_selinux_enabled:


##############################
# Temporary VM configuration #
##############################
## Name of the temporary VM to create. (default: "haikoo-temp-vm")
temp_vm_name:

## Name of the network to provision the vm on (default: "ovirtmgmt")
temp_vm_network: ""

## Number of cores to give the temporary vm (default: 2)
temp_vm_cores:

## Memory to give the temporary vm [in MB] (default: 2048)
temp_vm_memory:

## Number of retries (x30s) for template to complete operation (default: 20)
temp_vm_shutdown_retries:

############################
# Kubernetes Configuration #
############################
## The CRI-O Version to enable and install (default: 1.18)
crio_version: "1.18"
