---
- name: "Add ovirt engine endpoint {{ engine_endpoint | urlsplit('hostname') }} to inventory"
  hosts: localhost
  connection: local
  tasks:
    # Add ovirt engine host to inventory
    - name: "Add host {{ engine_endpoint | urlsplit('hostname') }} to inventory for better logging"
      add_host:
        name: "{{ engine_endpoint | urlsplit('hostname') }}"
        groups: ovirt

- name: "Run Preliminary checks and tests"
  hosts: ovirt
  connection: local
  roles:
    - pre_tasks
    - ovirt/connect
    - tests/ovirt

- name: "Provision the main virtual machine nodes"
  hosts: kube_main
  connection: local
  roles:
    - ovirt/import_facts
    - ovirt/wait_for_ip

- name: "Prepare the main nodes"
  hosts: kube_main
  gather_facts: yes
  tasks:
    - debug:
        msg: "{{ hostvars[item].ansible_host }}"
      with_list: "{{ groups['kube_main'] }}"
  #roles:
  #  - kubernetes/main_node_setup
