---
- name: "Run necessary preflight checks, and add ovirt engine as host"
  hosts: localhost
  connection: local
  roles:
    - checks/preflight

- name: "Add ovirt engine endpoint {{ engine_endpoint | urlsplit('hostname') }} to inventory"
  hosts: localhost
  connection: local
  tasks:
    # Add ovirt engine host to inventory
    - name: "Add host {{ engine_endpoint | urlsplit('hostname') }} to inventory for better logging"
      add_host:
        name: "{{ engine_endpoint | urlsplit('hostname') }}"
        groups: ovirt

- name: "Template setup tasks"
  hosts: ovirt
  connection: local
  roles:
    - ovirt/connect
    - checks/ovirt
    - ovirt/template

# - name: "Add dynamic hosts to inventory"
#   hosts: ovirt
#   connection: local
#   roles:
#     - add_hosts
#- name: "Import Template"
#  hosts: localhost
#  connection: local
#  roles:
#    - ovirt/connect
#    - ovirt/template
