---
- name: "Run necessary preflight checks, and add ovirt engine as host"
  hosts: localhost
  connection: local
  roles:
    - tests/preflight

- name: "Add ovirt engine endpoint {{ engine_endpoint | urlsplit('hostname') }} to inventory"
  hosts: localhost
  connection: local
  tasks:
    # Add ovirt engine host to inventory
    - name: "Add host {{ engine_endpoint | urlsplit('hostname') }} to inventory for better logging"
      add_host:
        name: "{{ engine_endpoint | urlsplit('hostname') }}"
        groups: ovirt

- name: "Template setup tasks"
  hosts: ovirt
  connection: local
  roles:
    - ovirt/connect
    - tests/ovirt
    - ovirt/template

- name: "Create an inventory of hosts"
  hosts: ovirt
  connection: local
  roles:
    - inventory

- hosts: kube_main
  connection: local
  roles:
    - ovirt/import_facts
    - ovirt/virtual_machine
    - ovirt/resize_disk
