---
- name: "Add ovirt engine endpoint {{ engine_endpoint | urlsplit('hostname') }} to inventory"
  hosts: localhost
  connection: local
  tasks:
    # Add ovirt engine host to inventory
    - name: "Add host {{ engine_endpoint | urlsplit('hostname') }} to inventory for better logging"
      add_host:
        name: "{{ engine_endpoint | urlsplit('hostname') }}"
        groups: ovirt

- name: "Run Preliminary checks and tests"
  hosts: ovirt
  connection: local
  roles:
    - pre_tasks
    - ovirt/connect
    - tests/ovirt
    - ovirt/template

- name: "Handle templating"
  hosts: ovirt
  connection: local
  roles:
    - ovirt/template

- name: "Create an inventory of hosts"
  hosts: ovirt
  connection: local
  roles:
    - inventory

- name: "Provision the main virtual machine nodes"
  hosts: kube_main
  connection: local
  roles:
    - ovirt/import_facts
    - ovirt/virtual_machine
    - ovirt/resize_disk
    - role: ovirt/virtual_machine
      state: started
