---
- name: "Run necessary preflight checks, and add ovirt host"
  hosts: localhost
  connection: local
  roles:
    - checks/preflight

- name: "Template setup tasks"
  hosts: ovirt
  connection: local
  roles:
    - ovirt/connect
    - checks/ovirt
    - ovirt/template

#- name: "Import Template"
#  hosts: localhost
#  connection: local
#  roles:
#    - ovirt/connect
#    - ovirt/template
