---
# Install packages
- name: "Install haproxy and keepalived"
  dnf:
    name:
      - haproxy
      - keepalived
    state: present
  become: yes

# This is all because the fucking nmcli module is broken.
- name: "Set fact to set the CIDR"
  set_fact:
    mask_cidr: "{{ ip | ipaddr('prefix') }}"
    ip_address: "{{ ansible_default_ipv4.address }}"
    interface: "{{ ansible_facts.default_ipv4.interface }}"
  vars:
    ip: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.netmask }}"

# Probably a bad use of the changed_when var
- name: "Run command set a static IP from the DHCP address"
  command: "nmcli con mod 'System {{ interface }}' ipv4.addresses '{{ ip_address }}/{{ mask_cidr }}'"
  become: yes
  register: nmcli_command
  changed_when: nmcli_command.rc != 0

# Template out /etc/hosts
- name: "Tempalate out the hosts file"
  template:
    src: hosts.conf.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: yes

# Ensure that /tmp/keepalived_pw does not exist
- name: "Ensure /tmp/keepalived_pw is absent so main node keepalived password can be makde"
  file:
    path: "/tmp/keepalived_pw"
    state: absent

# Template out Keepalived
- name: "Template out keepalived.conf"
  template:
    src: keepalived.conf.j2
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: yes


# Template out Keepalived
- name: "Template out haproxy.cfg"
  template:
    src: haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: yes

# Start and enable both services
- name: "Start and enable Haproxy and Keepalived"
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_list:
    - haproxy
    - keepalived
  when: inventory_hostname not in (groups['kube_main_removed'] | default(""))
  become: yes

# Restart services
# Throttle this to 1 to prevent downtime of all services at once.
- name: "Restart Haproxy and Keepalived to ensure config changes propagate"
  systemd:
    name: "{{ item }}"
    state: restarted
  with_list:
    - haproxy
    - keepalived
  when: inventory_hostname not in (groups['kube_main_removed'] | default(""))
  throttle: 1
  become: yes
