---
- name: "Import task to handle grabbing hosts from oVirt"
  ansible.builtin.import_tasks: grab_hosts.yaml


- name: "Import task to handle the difference calculation"
  ansible.builtin.import_tasks: calculate_differences.yaml


- name: "Import task to handle the creation of main nodes"
  ansible.builtin.import_tasks: new_main_nodes.yaml
  when:
    increase_main_nodes


- name: "Import task to handle the creation of worker nodes"
  ansible.builtin.import_tasks: new_worker_nodes.yaml
  when:
    increase_worker_nodes


- name: "Import task to handle the removal of main nodes"
  ansible.builtin.import_tasks: remove_main_nodes.yaml
  when:
    decrease_main_nodes


- name: "Import task to handle the removal of worker nodes"
  ansible.builtin.import_tasks: remove_worker_nodes.yaml
  when:
    decrease_worker_nodes
