---
# Gather a list of VMs and set them as kubernetes_control_plane_nodes_list, and kubernetes_worker_nodes_list
# Additionally, set new_cluster to False or New
- name: "Import task to gather virtual machines from oVirt"
  ansible.builtin.import_tasks: gather_vms.yaml


# Detect if a domain is set
- name: "Append a '.' to the domain variable if domain is set"
  ansible.builtin.set_fact:
    domain_tmp: ".{{ domain }}"
  when:
    domain is defined and
    domain | length > 0


# Manage control plane nodes
- name: "Import task to calculate needed control_plane_nodes"
  ansible.builtin.import_tasks: control_plane_nodes.yaml


# Manage worker nodes
- name: "Import task to calculate needed worker nodes"
  ansible.builtin.import_tasks: worker_nodes.yaml


- name: "Add facts to each host"
  ansible.builtin.import_tasks: add_facts.yaml
