# Create a certificate key for use later
- name: "Create certificate key"
  command: "kubeadm alpha certs certificate-key"
  register: certificate_key
  changed_when: certificate_key.rc != 0

# Set a fact to determine what the endpoint will be
- name: "Set a fact to determine whether to use the dns endpoint or IP endpoint"
  set_fact:
    endpoint: "{{ controlplane_dns_endpoint }}"
  when:
    - controlplane_dns_endpoint is defined and ( skip_dns_check or dns_check_passed )

# Set a fact to determine what the endpoint will be
- name: "Set a fact to determine whether to use the dns endpoint or IP endpoint"
  set_fact:
    endpoint: "{{ controlplane_endpoint }}"
  when:
    - controlplane_dns_endpoint is not defined

- name: "Initialize the cluster"
  command: |
    kubeadm init --pod-network-cidr=10.88.0.0/16
    --control-plane-endpoint {{ endpoint }}:6445
    --upload-certs
    --certificate-key {{ kubeadm_cert_key.stdout }}
  register: kube_init_cmd
  changed_when: kube_init_cmd.rc != 0

- name: "Get Join token"
  command: "kubeadm token create --print-join-command"
  register: join_command
  changed_when: join_command.rc != 0
