---
- name: "Start ovirt VM"
  ovirt_vm:
    auth: "{{ ovirt_auth }}"
    state: "running"
    name: "{{ inventory_hostname }}"
    cloud_init:
      host_name: "{{ inventory_hostname }}"
      authorized_ssh_keys: "{{ ssh_key }}"
      user_name: "{{ username }}"
      root_password: "{{ password }}"
      custom_script: |
        {% if runtime_commands is defined %}
        {{ runtime_commands }}
        {% else %}
        # DEBUG
        {% endif %}
