---
# Run a given command to enable cri-o
- name: "Enable cri-o version {{ crio_version }}"
  become: yes
  ansible.builtin.command:
    cmd: "dnf module enable -y cri-o:{{ crio_version }}"
    warn: no
  register: dnf_output
  changed_when: dnf_output.rc != 0

# Download and install cri-o
- name: "Install cri-o"
  become: yes
  ansible.builtin.dnf:
    name:
      - cri-o

# Change the default runtime to crun
- name: Change the default Runtime to crun
  become: yes
  ansible.builtin.lineinfile:
    path: "/etc/crio/crio.conf"
    regexp: '^default_runtime = "runc"$'
    line: 'default_runtime = "crun"'
    mode: u=rw,g=r,o=r

# Add crun to the runtimes
- name: "Add a runtime argument so that crun can be used"
  become: yes
  ansible.builtin.lineinfile:
    path: "/etc/crio/crio.conf"
    insertbefore: '\[crio\.runtime\.runtimes\.runc\]'
    line: "[crio.runtime.runtimes.crun]"
    mode: u=rw,g=r,o=r

# Disable SELinux for cri-o
- name: "Disable SELinux for cri-o"
  become: yes
  ansible.builtin.lineinfile:
    path:  "/etc/crio/crio.conf"
    regexp: '^selinux = true$'
    line: 'selinux = false'
    mode: u=rw,g=r,o=r
  when: not template_selinux_enabled
