---

# Grab the br_netfiter module
- name: "Modprobe the br_netfiter module"
  become: yes
  ansible.builtin.modprobe:
    name: br_netfilter
    state: present


# Ensure br_netfilter is loaded on boot
- name: "Add extra args to the kubelet sysconfig file"
  become: yes
  ansible.builtin.lineinfile:
    path: "/etc/modules-load.d/br_netfilter.conf"
    line: 'br_netfilter'
    state: present
    create: yes
    owner: root
    group: root
    mode: u=rw,g=r,o=r


# Sysctl stuff
- name: "Set required sysctl variables"
  become: yes
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.conf
  with_dict:
    net.ipv4.ip_forward: 1
    net.bridge.bridge-nf-call-ip6tables: 1
    net.bridge.bridge-nf-call-iptables: 1
    net.ipv4.ip_nonlocal_bind: 1
