---
# Module to loop over until the specified virtual machine has been given an IP address
- name: "Query oVirt for virtual machine IP address"
  ovirt.ovirt.ovirt_nic_info:
    auth: "{{ ovirt_auth }}"
    vm: "{{ inventory_hostname }}"
    nested_attributes:
      - 'reporteddevices'
    name: '*'
  register: ovirt_nic_info
  until: ovirt_nic_info.ovirt_nics[0].reported_devices[0].ips is defined
  delay: 60
  retries: "{{ startup_timeout }}"

- name: "Set the ansible_host fact from the returned IP information"
  ansible.builtin.set_fact:
    ansible_host: "{{ item.address }}"
  with_list: "{{ ovirt_nic_info.ovirt_nics[0].reported_devices[0].ips }}"
  when: item.version == 'v4' and item.address != controlplane_endpoint
