###############
# Engine vars #
###############
ovirt_engine_username: "admin@internal"
ovirt_engine_datacenter_name: "Default"
ovirt_engine_cluster_name: "Default"
startup_timeout: 60
username: "kubeadmin"
#################
# Template vars #
#################
template_name: "k8s"
template_subversion_name: "post-modification"
template_storage_location: "data"
template_import_timeout: 600
template_description: "Created by haikoo"
template_timezone: "Etc/GMT"

template_upgrade_packages: True
template_selinux_enabled: False


##############################
# Temporary VM configuration #
##############################
temp_vm_name: "haikoo-temp-vm"
temp_vm_network: "ovirtmgmt"
temp_vm_cores: 6
temp_vm_memory: 3072
temp_vm_shutdown_retries: 45

############################
# Kubernetes Configuration #
############################
crio_version: "1.18"
