###############
# Engine vars #
###############
engine_username: "admin@internal"
engine_datacenter_name: "Default"
engine_cluster_name: "Default"

#################
# Template vars #
#################
template_name: "k8s"
template_storage_location: "data"
template_import_timeout: 600
template_description: "Created by haikoo"
template_timezone: "Etc/GMT"
template_upgrade_packages: True
template_selinux_enabled: False
template_services:
  - "kubelet"
  - "crio"
  - "logrotate.timer"
template_packages:
  - "qemu-guest-agent"
  - "dnf-automatic"
  - "nfs-utils"
template_commands:
  - "modprobe br_netfilter"
  - "echo 'br_netfilter' >> /etc/modules-load.d/br_netfilter.conf"
  - "echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.d/k8s.conf"
  - "echo 'net.bridge.bridge-nf-call-ip6tables=1' >> /etc/sysctl.d/k8s.conf"
  - "echo 'net.bridge.bridge-nf-call-iptables=1' >> /etc/sysctl.d/k8s.conf"
  - "echo 'KUBELET_EXTRA_ARGS=--cgroup-driver=systemd --container-runtime=remote --container-runtime-endpoint=\"unix:///var/run/crio/crio.sock\"' >> /etc/sysconfig/kubelet"
  - "grubby --update-kernel=ALL --args='systemd.unified_cgroup_hierarchy=0'"
  - "yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes"
  - "dnf module enable -y cri-o:{{ crio_version }}"
  - "dnf install -y cri-o kubernetes-cni logrotate ceph-common"

##############################
# Temporary VM configuration #
##############################
temp_vm_name: "haikoo-temp-vm"
temp_vm_network: "ovirtmgmt"
temp_vm_cores: 4
temp_vm_memory: 2048
temp_vm_shutdown_retries: 20

############################
# Kubernetes Configuration #
############################
crio_version: "1.18"


###########################################
# Clout-init configuration. Needs cleanup #
###########################################
temp_vm_cloudinit: |
  yum_repos:
  {% if template_extra_repos is defined %}
  {% for repository in template_extra_repos %}
    {{ repository.name }}:
        baseurl: {{ repository.url }}
        enabled: true
        gpgcheck: true
        gpgkey: {{ repository.gpgkey }}
        name: {{ repository.name }}
  {% endfor %}
  {% endif %}
    kubernetes:
      url: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
      gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
      name: "Kubernetes"
  {% if template_upgrade_packages %}
  package_update: true
  package_upgrade: true
  {% endif %}
  packages:
  {% for package in template_packages %}
   - {{ package }}
  {% endfor %}
  {% if template_extra_packages is defined %}
  {% for package in template_extra_packages %}
    - {{ package }}
  {% endfor %}
  {% endif %}
  runcmd:
  {% if not template_selinux_enabled %}
   - sed -i 's/enforcing/disabled/g' /etc/selinux/config /etc/selinux/config
  {% endif %}
  {% for command in template_commands %}
   - {{ command }}
  {% endfor %}
  {% if template_extra_commands is defined %}
  {% for extra_command in template_extra_commands %}
   - {{ extra_command }}
  {% endfor %}
  {% endif %}
  {% for unit in template_services %}
   - systemctl enable {{ unit }}
  {% endfor %}
  final_message: "The system is finally up, after $UPTIME seconds"
  power_state:
    delay: "0"
    mode: poweroff
    message: Bye Bye
    timeout: 30
    condition: True
