---
- name: "Import role to gather information on the Cluster and Datacenter"
  ansible.builtin.import_role:
    name: common/gather-env-info/dc_cluster


- name: "Import role to gather information on storage"
  ansible.builtin.import_role:
    name: common/gather-env-info/storage


- name: "Import role to gather information on networks"
  ansible.builtin.import_role:
    name: common/gather-env-info/networks


- name: "Import role to gather information on templates"
  ansible.builtin.import_role:
    name: common/gather-env-info/templates


- name: "Import role to gather information on virtual machines"
  ansible.builtin.import_role:
    name: common/gather-env-info/virtual_machines
