# Grab information for the ovirt disks
- name: "Get disk info for {{ inventory_hostname }}"
  ovirt_disk_info:
    auth: "{{ ovirt_auth }}"
    pattern:
      vm_names={{ inventory_hostname }}
  register: disk_info

# Set the size of the disk
- name: "Get disk info for {{ inventory_hostname }}"
  ovirt_disk:
    auth: "{{ ovirt_auth }}"
    id: "{{ disk_info.ovirt_disks[0].id }}"
    name: "root_{{ inventory_hostname }}"
    vm_name: "{{ inventory_hostname }}"
    description: "Root filesystem for {{ inventory_hostname }}"
    size: "{{ disk_size }}GiB"
